sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
- 3.6-dev
- pypy
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - python: pypy3
  include:
  - python: 3.6
    env: TOXENV=pre-commit
  - python: pypy3
    env: PYPY_VERSION=pypy3.5-5.7.1-beta
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - make
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - tk-dev
    before_install:
    - |
      export PYENV_ROOT="$HOME/.pyenv"
      if [ -f "$PYENV_ROOT/bin/pyenv" ]
      then
        pushd "$PYENV_ROOT" && git pull && popd
      else
        rm -rf "$PYENV_ROOT" \
        && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
      fi
      "$PYENV_ROOT/bin/pyenv" install "$PYPY_VERSION"
      "$PYENV_ROOT/versions/$PYPY_VERSION/bin/pip" install -U setuptools pip
      virtualenv --python="$PYENV_ROOT/versions/$PYPY_VERSION/bin/python" \
                 "$HOME/virtualenvs/$PYPY_VERSION"
      source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
    - pip install -U 'setuptools<30' six
cache:
  pip: true
  directories:
  - "$HOME/.pre-commit"
  - "$HOME/.pyenv"
before_install: pip install -U setuptools
install: pip install -U -r requirements-dev.txt
script: |
    if [[ $TOXENV == pre-commit ]]
    then
        pre-commit run --all-files
    else
        pytest aiohttp_ripozo/tests.py -vv
    fi
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.6
  user: webknjaz
  distributions: dists
  skip_upload_docs: true
  password:
    secure: WnMZ34Oktp9fBtQZPjaBbpK9won00+CwDc5XU26ztls/OTdt4zpy1vM6G8lu56DYjI3kJplQt9T0D9Zoxw+qR6eV7YoZUP2v5aWXRLl79CVJFzcEwYr1089w02o1BJ9DqlJLW+dL+w6oWLo9T80TbelkDzXSVRArZ87GU5NzTCapHip+UVdwj+1DJMPCiphDQTX0fRjZ7l5k65nSv7ANcYmlDKjSWGXuIKMXIqSrUtOxyVk3N37/lEtpJJrx+eSvuHhvsICjMpcIfpWB6sMp4pBqHIAmm1nmMs7kOBbpZIheXcuEDUP4ox52DAqJrM7n9RjmcCNSGFX9oTxFdedMUF4CHsgnT6sz7SQT30vGywF2rOcqUFFDVyykN7Bf64ewHBj91s/3R1GxBPJOBAPVAKgVG4i/WMO9tRYchyLjZ9aAWPlh1ZYc2ihYKcrBdE0xK9hg1021EkBmmdghwREtyeORXWOQEVA4YKkQx9wu4OfAdQVWjJI3nJ0bMm1PqbWkDCkGeF1z46ZMsLnfHQ6X9n6p4xmGKB9WW2/U6o6jZXAK+tgyafjypdLbbgTIXTZ8e/NegcpzLNfmpYMnc71kEEInTuVsiZDUhJ15hTki8fONMA9q1IbKTsQ1pmKaIpyPxWgeKRT8nCosC2G4PkUODIkRlCMFezDZ2YPm9ybi0Ug=
